on: [push]

name: push-action

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master

